using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Component dependencies
[RequireComponent(typeof(Rigidbody2D))]
[RequireComponent(typeof(CollisionSensor))]

public class GroundMovement : MonoBehaviour, MovementInterface
{
  //=== Params
  [Tooltip("Whether to invert the direction the character faces")]
  [SerializeField] bool invertFacingDirection;

  [Tooltip("The base speed in which the character moves")]
  [SerializeField] float baseSpeed = 5f;

  [Tooltip("Vertical velocity to add on jump")]
  [SerializeField] float jumpPower = 10f;

  //=== State

  // Stores how much movement was applied in this frame
  float frameMovement;

  // Stores how much movement was applied last frame
  float lastFrameMovement;

  //=== Refs
  Rigidbody2D _rigidbody;
  CollisionSensor _collisionSensor;

  private void Awake()
  {
    // Get components
    GetComponentRefs();
  }

  private void LateUpdate()
  {
    lastFrameMovement = frameMovement;
    frameMovement = 0f;
  }

  private void UpdateFacingDirection(float movement)
  {
    // Ignore small movements
    if (Mathf.Abs(movement) > 0.1f)
    {
      // Keep facing direction updated
      SetFacingDirection(movement);
    }
  }

  private void GetComponentRefs()
  {
    _rigidbody = GetComponent<Rigidbody2D>();
    _collisionSensor = GetComponent<CollisionSensor>();
  }

  //=== Interface

  // Apply movement to character. The movementModifier param can alter the direction as well as the speed
  public void Move(float movementModifier)
  {
    float movement = baseSpeed * movementModifier;

    // Apply it
    _rigidbody.velocity = new Vector2(movement, _rigidbody.velocity.y);

    // Adjust move direction
    UpdateFacingDirection(movement);

    // Record this movement
    frameMovement = movement;
  }

  // Informs how much movement was generated by the Move method in the last frame
  public float GetLastFrameMovement()
  {
    return lastFrameMovement;
  }

  // Update facing direction
  public void SetFacingDirection(float direction)
  {
    float directionModifier = invertFacingDirection ? -1 : 1;
    transform.localScale = new Vector2(Mathf.Sign(direction) * directionModifier, 1f);
  }

  // Jump method
  public void Jump()
  {
    // Ensure it's grounded
    if (!_collisionSensor.IsGrounded()) return;

    // Add y velocity
    _rigidbody.velocity = new Vector2(_rigidbody.velocity.y, jumpPower);
  }
}
